### PR TITLE
Fix project resource service implementation

### PR DESCRIPTION
**Pull request by KochTobi**
Many thanks for contributing to this project!

**PR Checklist**
Please fill in the appropriate checklist below (delete whatever is not relevant). These are the most common things requested on pull requests (PRs).

- [x] This comment contains a description of changes (with reason)
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [ ] `CHANGELOG.rst` is updated

**Description of changes**
The add project resource service did not modify its content. This was not caught by the tests.
This PR introduces the missing tests and implementation of the missing behaviour.

### CODE REVIEW

**Comment by jenniferboedker** [comment]
please add a description of your changes so that its easier for me to understand what your goal was

**Review by jenniferboedker — APPROVED** [review]
lgtm but next time please provide a small description of your changes ;)

**Comment by KochTobi** [comment]
> lgtm but next time please provide a small description of your changes ;)

The add project resource service did not modify its content. This was not caught by the tests.
This PR introduces the missing tests and implementation of the missing behaviour.

It was there all along ;)

**Comment by jenniferboedker** [comment]
sorry I obviously oversaw that 🙈 

> The add project resource service did not modify its content. This was not caught by the tests.
> This PR introduces the missing tests and implementation of the missing behaviour.
> 
> It was there all along ;)

**Pull request merged**
