### PR TITLE
Visually indicate project status

### PR DESCRIPTION
**Pull request by jenniferboedker**
This PR introduces the feature of indicating the project status by color. 

- [X] Extend the project summary (#101)
- [x] Show total sample count in view (#104)
- [x] Set default color to grey (#102)
- [x] Completed statuses are shown in green (#102)
- [x] Failing QC is indicated in red (#102)

### CODE REVIEW

**Comment by KochTobi** [comment]
image
This is what it would look like with the following colors:
```
//$v-friendly-color: #2c9720;
//$v-error-indicator-color: #ed473b;
```

**Comment by jenniferboedker** [comment]
> image
> This is what it would look like with the following colors:
> 
> ```
> //$v-friendly-color: #2c9720;
> //$v-error-indicator-color: #ed473b;
> ```

What is the color of the grey? It looks bluish to me 🤔

**Comment by KochTobi** [comment]
`#cbd5e8` as suggested by color brewer 😄

**Comment by jenniferboedker** [comment]
Hi @KochTobi and @Steffengreiner 
thanks for your great work! I am happy with how it currently looks. I updated the colors to make them more apparent. 
Is it possible to center the sample count?

**Comment by KochTobi** [comment]
> Hi @KochTobi and @Steffengreiner
> thanks for your great work! I am happy with how it currently looks. I updated the colors to make them more apparent.
> Is it possible to center the sample count?

I think it should be doable by adding `text-align: center;` to the css

**Comment by jenniferboedker** [comment]
Since created this PR I cannot approve this card maybe someone else of the @qbicsoftware/itss members could do that?

**Review by KochTobi — APPROVED** [review]

**Pull request merged**
