### PR TITLE
Reset file downloader after selection change

### PR DESCRIPTION
**Pull request by KochTobi**
Fixes manifest files not being reset properly after project selection change.

### CODE REVIEW

**Review by jenniferboedker — CHANGES_REQUESTED** [review]
Hi Tobi, thanks for looking into it! The duplicated download is not fixed but I get an error message if I select another project with available data. (See screenshot)

Screenshot 2021-12-10 at 08 25 02

`10.12.2021 08:24:52 [ERROR] [ProjectOverviewView] - An error occured whily trying to download Optional.empty
10.12.2021 08:24:52 [ERROR] [ProjectOverviewView] - Manifest Download failed due to: Could not forward results for QABCD`

I think the values are not reset properly

**Comment by KochTobi** [comment]
Hmm it worked before I merged development

**Comment by KochTobi** [comment]
> Hi Tobi, thanks for looking into it! The duplicated download is not fixed but I get an error message if I select another project with available data. (See screenshot)
> 
> Screenshot 2021-12-10 at 08 25 02
> 
> `10.12.2021 08:24:52 [ERROR] [ProjectOverviewView] - An error occured whily trying to download Optional.empty 10.12.2021 08:24:52 [ERROR] [ProjectOverviewView] - Manifest Download failed due to: Could not forward results for QABCD`
> 
> I think the values are not reset properly

It seems I introduced a concurrent modification exception by accident after the merge. Can you have another look please?

**Review by jenniferboedker — APPROVED** [review]
Works now, thanks!

**Pull request merged**
